---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: sachinkumar2507/capstone:1.01
          name: myweb
          ports:
            - containerPort: 8081
          env:
          - name: SQL_URL
            value: mysql-0.sql-headless.default.svc.cluster.local
          - name: SQL_PORT
            value: "3306"
          - name: SQL_USR
            value: "user"
          - name: SQL_PW
            value: "root@1234"
          - name: SQL_TABLE
            value: "mydb"
#################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: myweb
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000
    protocol: TCP
  selector:
    app: capstone

---
apiVersion: v1
kind: Service
metadata:
  name: sql
  labels:
    app: myweb


spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: sql
